### ISSUE TITLE
Atypical behavior of `hexStringToBytes` leads to inconsistent data

### ISSUE THREAD

**Issue by kcchu** [farcasterxyz/hub#443]
**What is the bug?**

The function name `hexStringToBytes` (in `packages/utils/src/bytes.ts`) suggested that it is a function that converts a hex string into a byte array. It is a function used very frequently in the codebase. However, the current implementation deviated from usual expectation in two ways:

1. The output bytes array is reversed by default: `"0x010203" -> [3, 2, 1]`
2. Leading zeros are removed: `"0x000001" -> [1]`

**How can it be reproduced? (optional)**

The following code intended to test the string format of SyncId. Note the string representation of SyncId contains the hex of hash in reversed order.

```typescript
  test('create syncId with expected format', async () => {
    const fid = Factories.FID.build();
    const date = new Date(1665182332000);
    const hash =
      '0x09bc3dad4e7f2a77bbb2cccbecb06febfc3f0cbe7ea6a774d2dc043fd45c2c9912f130bf502c88fdedf7bbc4cd20b47aab2079e2d5cbd0a35afd2deec86a4321';

    const id = await NetworkFactories.SyncId.create(undefined, {
      transient: { fid, date, hash },
    });

    expect(id.idString()).toEqual(
  '166518233201000000000000000000000000000000000000000000000000000000000000a2b80e6340aa7c21436ac8ee2dfd5aa3d0cbd5e27920ab7ab420cdc4bbf7edfd882c50bf30f112992c5cd43f04dcd274a7a67ebe0c3ffceb6fb0eccbccb2bb772a7f4ead3dbc09'
    );
```

**Additional context (optional)**

The change that caused this issue referenced #375 which is about fixing endianness of data. But hex string should simply be a representation of byte array in same sequence where endianness (i.e. byte representation of a CPU word/number) has no effect. This behavior currently causes hashes and signature to be invalidated in multiple cases.

For example, leading 0 in a hash occurs roughly 1 in 256 chance. Removing the 0 from a hex representation of hash will cause the hash to fail to match.

**Comment by pfletcherhill** [comment]
I agree those methods are atypical and am certainly open to suggestions for improving them. We've had multiple problems in the past due to not enforcing endianness or padding (mostly due to ethereum primarily using big endian and us wanting to use little endian), so these are the conventions we've tried to implement:
* Byte arrays should be unpadded little endian order
* Hex strings, whenever used, should represent big endian ordered byte arrays and be padded (open to changing this, though the main area we use hex is for interacting with ethereum libraries which need big endian order)
* Rocksdb keys should be padded, big endian byte arrays to enable lexicographic ordering

Also worth noting that in practice we try to generate fixed size big endian hex strings given the particular context. So while we'd strip the padding from a 32 byte hash when storing it, we'd add the padding back when converting it back into a hex string.

**Comment by pfletcherhill** [comment]
Assigned myself to take a deeper look at this

**Comment by pfletcherhill** [comment]
This should be addressed with protoutils (the protobufs version of the utils package). I replaced the custom methods with [more standard ones](https://github.com/farcasterxyz/hub/blob/2e32983f075f0f8a7d7ed9b68bf6a7f04ae31143/packages/protoutils/src/bytes.ts#L90) (just using noble's `bytesToHex` and `hexToBytes`) and don't try to enforce byte order or padding in utils.
