### ISSUE TITLE
feat: hub should implement a binary protocol to communicate with each other

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#65]
Hubs should be able to encode and pass messages via a highly efficient transport protocol like protobuf, flatbuffers or [capnproto](https://github.com/capnproto/capnproto)

**Comment by sds** [comment]
When considering solutions, it's worth exploring whether we can have the on-disk format of of the stored messages mirror that of what is sent over the wire, as that would allow us to serve directly from disk very efficiently using [`sendfile`](https://man7.org/linux/man-pages/man2/sendfile.2.html). 

We would still be able to annotate these messages with other data structures (whether those are in memory or elsewhere) but could then very quickly send the data to minimize CPU load incurred due to syncing. The limiting factor would then be how quickly the hub receiving these messages can process + validate the messages, but the sending hub incurs very little performance cost, a good thing if you want to encourage hub operators to be willing to share their Farcaster data with other hubs.
